// <auto-generated />
namespace Layers.Data.DataAccess.Migrations.Read
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addsectionview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsectionview));
        
        string IMigrationMetadata.Id
        {
            get { return "202008050026018_addsectionview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
